### ISSUE TITLE
Wrong storage requirements claimed in GUI Intro

### ISSUE THREAD

**Issue by grubles** [greenaddress/elements#1]
### Describe the issue
Text strings from Core are included and don't match the storage requirements for Elements / Liquid.
#### If so, please list the steps to reproduce below:
1. Start -QT for the first time.

### Expected behaviour
Should more accurately state the storage requirements (~600 MB on my machine).
### Actual behaviour
The GUI displays the storage requirements as ~120 GB, which isn't accurate. 
### Screenshots
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.
<img width="674" alt="screen shot 2019-02-15 at 12 21 30 pm" src="https://user-images.githubusercontent.com/7411154/52904564-ac5f7480-31fb-11e9-9ff9-7fef0cde6fae.png">

### Machine specs:
- OS: macOS Mojave

**Comment by luke-jr** [comment]
Fixed in 3426ca1f4dbab852f794dafc27959c9c2b113762
