### ISSUE TITLE
Splash Screen - Change Copyright Years

### ISSUE THREAD

**Issue by bitschmidty** [greenaddress/elements#10]
Change copyright years from 2015-2017 to 2015-2019

<img width="592" alt="screen shot 2019-02-27 at 10 47 12 am" src="https://user-images.githubusercontent.com/1615772/53507225-1c33f180-3a7d-11e9-8261-b98403747e3c.png">

**Comment by bitschmidty** [comment]
The "About liquid-qt" should be changed as well

**Comment by luke-jr** [comment]
Fixed in 1164cc432a05fbd2a47f0b35d575f945935c3e3c
