### ISSUE TITLE
Recent Transactions Dialog - Change text from Bitcoin to Liquid

### ISSUE THREAD

**Issue by bitschmidty** [greenaddress/elements#11]
1. "This information will be correct once your wallet has finished synchronizing with the *Liquid* network, as detailed below."
1. "Attempting to spend *assets* that are affected by not-yet-displayed transactions will not be accepted by the network."

<img width="962" alt="screen shot 2019-02-27 at 10 46 11 am" src="https://user-images.githubusercontent.com/1615772/53507748-0f63cd80-3a7e-11e9-81a7-f566e1c4a55f.png">

**Comment by luke-jr** [comment]
Fixed in b99e8f8595587095978dd9650d3fa5894bf73b46
