### ISSUE TITLE
Receive Tab - Show button disabled

### ISSUE THREAD

**Issue by bitschmidty** [greenaddress/elements#12]
Show button on the receive screen is disabled. 

Double clicking on the address correctly brings up the request payment address details dialog. This is what should be shown then the Show button is functional. 

<img width="1087" alt="screen shot 2019-02-27 at 11 02 01 am" src="https://user-images.githubusercontent.com/1615772/53508317-20f9a500-3a7f-11e9-87e2-0b969f731fb9.png">

**Comment by greenaddress** [comment]
I think is because of bitcoin uri equivalent not being in scope

**Comment by bitschmidty** [comment]
bitcoinuri is only one of the fields on the dialog. If it is more difficult to rework the dialog, perhaps we can just add the address to the "Requested payments history" table.

**Comment by luke-jr** [comment]
Fixed in 4a3fb7a3e61160f9da66234919c91a1fe2e2a05e
