### ISSUE TITLE
Receive Tab - Remove button disabled

### ISSUE THREAD

**Issue by bitschmidty** [greenaddress/elements#13]
Similar to #12 but with remove button. Unsure if this disabling is intentional or bug.

<img width="1087" alt="screen shot 2019-02-27 at 11 02 01 am" src="https://user-images.githubusercontent.com/1615772/53508514-851c6900-3a7f-11e9-9890-f316effe600f.png">

**Comment by luke-jr** [comment]
Fixed in 4a3fb7a3e61160f9da66234919c91a1fe2e2a05e
