### ISSUE TITLE
Status bar - Connections tooltip - Change Bitcoin to Liquid

### ISSUE THREAD

**Issue by bitschmidty** [greenaddress/elements#14]
Change "Bitcoin" network to "Liquid" in the connections status bar tooltip.

<img width="484" alt="screen shot 2019-02-27 at 11 06 33 am" src="https://user-images.githubusercontent.com/1615772/53508713-eb08f080-3a7f-11e9-9a2a-4e0491d6e404.png">

**Comment by bitschmidty** [comment]
Similarly the "Pay only the required fee..." on the send screen has bitcoin instead of Liquid reference

**Comment by greenaddress** [comment]
agree with @bitschmidty

**Comment by luke-jr** [comment]
Fixed in 71c0514a89243baa946cbc8d1da87c5d783b4398 and 5a51b98ed469cf5ca6c931057971298195e31d03
