### ISSUE TITLE
System notification show L-BTC even when sending/receiving assets

### ISSUE THREAD

**Issue by domegabri** [greenaddress/elements#16]
When sending/receiving an asset, notifications show the amount with L-BTC units.

Note also the "**(GUI node for bitcoin)**" in the second screenshot.

### Screenshots.

- macOS 10.14

<img width="330" alt="notification_macos" src="https://user-images.githubusercontent.com/42006886/53561071-24a82d00-3b4e-11e9-8a53-e9c9f5743a40.png">

- Windows 10

<img width="330" alt="notification_windows" src="https://user-images.githubusercontent.com/42006886/53561093-34277600-3b4e-11e9-9cac-6c26825da68f.png">

### Version

1164cc432a05fbd2a47f0b35d575f945935c3e3c

### Machine specs:

Tested on a physical machine running macOS 10.14 Mojave and a virtual machine running Windows 10

**Comment by greenaddress** [comment]
agreed

**Comment by luke-jr** [comment]
Fixed in 0fd7c136c9d1630ce491f4eda0659e102331fdc9 and 069b92b796e6c3e1de5a7dc0fb3176813ae5d8a3
