### ISSUE TITLE
Startup error shown if bitcoind RPC unavailable is unclear to newbies

### ISSUE THREAD

**Issue by valerio-vaccaro** [greenaddress/elements#2]
### Describe the issue
Once the liquid-qt is launched, if the bitcoin server is not correctly configured, the app displays an ambiguous error message. A user may not adequately understand the need to install a bitcoin node.

#### If so, please list the steps to reproduce below:
Start liquid-qt  app without other arguments (and without a configuration file).

### Expected behaviour
Suggest to install bitcoin core (maybe with a link to bitcoincore.org) and to configure liquid appropriately. 

### Actual behaviour
Show an error message and halt the app.

### Screenshots
<img width="488" alt="schermata 2019-02-18 alle 17 01 28" src="https://user-images.githubusercontent.com/2773110/52963269-912d6a00-339f-11e9-8dbb-267f1d98003a.png">

### Machine specs:
MacOSX 10.14.3

**Comment by luke-jr** [comment]
Does it make sense for normal users to verify pegins? Maybe it should be disabled by default unless mining?

**Comment by luke-jr** [comment]
@greenaddress pointed out that pegins are needed to verify unconfirmed transactions.

**Comment by greenaddress** [comment]
I would keep the error and add to it:

"If you haven't setup a bitcoind please get the latest stable version from https://bitcoincore.org/en/download/ or if you do not need to validate pegins
set in your liquid configuration validatepegin=0"

**Comment by luke-jr** [comment]
Fixed in 4532fb5feda3391494498fbeca801d8b89700042

**Comment by bitschmidty** [comment]
I think we need the config file location for newbie users.

"If you haven't setup a bitcoind please get the latest stable version from https://bitcoincore.org/en/download/ or if you do not need to validate pegins,
set 'validatepegin=0' in a liquid configuration file (located at %s/liquid.conf)"
