### ISSUE TITLE
Changing l-BTC units causes a crash

### ISSUE THREAD

**Issue by domegabri** [greenaddress/elements#3]
### Description

Changing l-BTC causes a crash. At the next start, units are updated.

#### Steps to reproduce
1. Start liquid-qt
2. Change l-BTC units

### Expected behaviour
Units updated across the app

### Actual behaviour
Crash

### Version

3.14.1.22 aff772d

### Machine specs:
- OS: macos 10.14

### Any extra information that might be useful in the debugging process.

`Abort trap: 6` printed after the crash

**Comment by luke-jr** [comment]
Fixed in d8c05b87776d957af099e8110ea2870510e68fe8
