### ISSUE TITLE
SubtractFeeFromAmount checkbox shown when sending asset

### ISSUE THREAD

**Issue by domegabri** [greenaddress/elements#4]
### Description
The SubtractFeeFromAmount checkbox is shown even when choosing an asset different than L-BTC

#### Steps to reproduce below:
1. Go to send tab
2. Select an asset different from L-BTC from the dropdown

### Expected behaviour
Checkbox greyed out or hidden

### Actual behaviour
Checkbox is shown and can be enabled

### Screenshot
<img width="994" alt="subtract_fee_from_amount" src="https://user-images.githubusercontent.com/42006886/52972205-64d31700-33ba-11e9-9680-850c2fd55307.png">

### Version

3.14.1.22 aff772d

### Machine specs:
- OS: macos 10.14

**Comment by luke-jr** [comment]
Fixed in 634c9a08a7877dfd6736b12c092a1472792e2a98
