### ISSUE TITLE
Minus sign after decimal point in overview tab and transactions tab

### ISSUE THREAD

**Issue by domegabri** [greenaddress/elements#5]
### Description
Minus sign shown after decimal point in amounts (tx overview tab and transactions tab). Seems to happen only for very low amounts. Attached screenshot

### Screenshot

In overview tab:

<img width="1317" alt="recent_txs_to_rick" src="https://user-images.githubusercontent.com/42006886/52972354-f04ca800-33ba-11e9-85bd-8dca3123e554.png">

In transactions tab:

<img width="1342" alt="screenshot 2019-02-18 at 20 29 33" src="https://user-images.githubusercontent.com/42006886/52972693-f55e2700-33bb-11e9-8aa2-1f47009eaf95.png">

### Version

3.14.1.22 aff772d

### Machine specs:
- OS: macos 10.14

**Comment by luke-jr** [comment]
Fixed in a2ff55af59f25f1bf11c5f3bb7ee257872132d9d
