### ISSUE TITLE
Sent amount in transaction details is always shown in L-BTC units

### ISSUE THREAD

**Issue by domegabri** [greenaddress/elements#6]
### Description

If the asset sent is not L-BTC, amount units are still shown in L-BTC.

#### Steps to reproduce:

Go to transactions tab and double click on a transaction

### Expected behaviour
Apply units only for L-BTC and show asset id

### Screenshots.

<img width="609" alt="mbtc_unit_for_asset" src="https://user-images.githubusercontent.com/42006886/52973161-7b2ea200-33bd-11e9-989d-85ee6a19e47d.png">

### Version

3.14.1.22 aff772d

### Machine specs:
- OS: macos 10.14

**Comment by luke-jr** [comment]
Removed the "transaction details" display for now. (in 1afe9ce6399839ab192183c0f2cfeb41f252f983)
