### ISSUE TITLE
Transaction id not available

### ISSUE THREAD

**Issue by domegabri** [greenaddress/elements#8]
After 1afe9ce6399839ab192183c0f2cfeb41f252f983, there is no way to see a transaction ID beside exporting a .csv file.

### Expected behaviour
It would nice to have the tx id shown somewhere in the app. Or allowing copy to clipboard.

It could be an additional column in the transaction list tab or copying directly to the clipboard the txid when clicking on an entry in the table.

### Version 
2e82bda
### Machine specs:
- OS: macOS 10.14

**Comment by luke-jr** [comment]
Works fine for me? Right click on a transaction -> Copy transaction ID

**Comment by greenaddress** [comment]
closing, thanks @luke-jr
